-- Create Tables
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text, bio text, website text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  post_id uuid references public.posts on delete cascade not null,
  unique(user_id, post_id)
);

create table public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  post_id uuid references public.posts on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS (Security)
alter table public.profiles enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;